# Generated by Django 2.2.7 on 2020-01-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200107_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_image',
            field=models.TextField(default='https://halbertcontracting.com/wp-content/uploads/2015/12/129-750x300-1.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
